### PR TITLE
add dac_name query param

### PR DESCRIPTION
**Pull request by rkamysz**
The purpose of this PR is to replace custom header `X-DAC-Name` with regular query param `dac_name` in the `/profile` request

```
// before
curl -X GET "http://127.0.0.1:41629/v1/eosdac/profile?account=1x2qw.wam" -H  "accept: application/json" -H "X-DAC-Name: nerix"

// current
curl -X GET "http://127.0.0.1:41629/v1/eosdac/profile?account=1x2qw.wam&dac_name=nerix"
```

### CODE REVIEW

**Review by dallasjohnson — APPROVED** [review]

**Review by dallasjohnson — CHANGES_REQUESTED** [review]
For consistency could we change `dac_name` to `dac_id`. This is how it's specified [here](https://wax.bloks.io/account/index.worlds?loadContract=true&tab=Tables&account=index.worlds&scope=index.worlds&limit=100) and will avoid confusion going forward if we keep it consistent.

**Review by dallasjohnson — APPROVED** [review]
LGTM. Would it be hard to make this a path param rather than a query param? I feel this might be cleaner. It could be a separate PR.

**Comment by rkamysz** [comment]
No it's easy change... but which pattern:
```
/profile/:account/:dacId    or    /profile/:account?dacId=some_id
```
?

If we do not have more options in the request, we can use the first variant ... if we have more filter options, we should use query params so we won't force the user to remember the order and insert parameters that he does not need... only because of the path structure

**Comment by dallasjohnson** [comment]
I was thinking more like `/profile/:dacId?account=account_id1&account=account_id2` This could then be used (later) to fetch a batch of profiles if the query param was missing or get one profile or many profiles if they are requested by `account` individually.

**Pull request merged**
